export const data = {
    logo: 'Logo',
    header1: 'The Eminence in Shadow (Kage no Jitsuryokusha ni Naritakute) Chapter 47: Release Date, Raw Scans, Spoilers, Read Online',
    title1: 'For mind',
    left1: 'self care',
    right1: 'A day ago',
    description1: 'Lorem ipsum, consectetur adipiscing elit.',
    title2: 'For soul',
    left2: 'self care',
    right2: 'A day ago',
    description2: 'Lorem ipsum, consectetur .',
    title3: 'For body',
    left3: 'self care',
    right3: 'A day ago',
    description3: 'Lorem ipsum, consectetur adipiscing elit.',
    picText1: 'Lorem ipsum dolor sit amet.',
    picText2: 'Lorem ipsum dolor sit amet.',
    picText3: 'Lorem ipsum dolor sit amet.',
    picText4: 'Lorem ipsum dolor sit amet.',
    header2: 'Join our community',
    header3: 'Join us on patreon',
    para1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    header4: 'Participate in our events',
    para2: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. sit amet, consectetur adipiscing elit.',
    picText5:'Lorem ipsum dolor sit amet.',
    picText6:'Lorem ipsum dolor sit amet.',
    picText7:'Lorem ipsum dolor sit amet.',
    picText8:'Lorem ipsum dolor sit amet.',
    picText9:'Lorem ipsum dolor sit amet.',
    picText10:'Lorem ipsum dolor sit amet.',
    picText11:'Lorem ipsum dolor sit amet.',
    picText12:'Lorem ipsum dolor sit amet.',
    picText13:'Lorem ipsum dolor sit amet.',
    picText14:'Lorem ipsum dolor sit amet.',
    picText15:'Lorem ipsum dolor sit amet.',
    footText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla est purus, ultrices in porttitor in, accumsan non quam.",
}